import React, { useEffect, useState, useContext } from 'react';
import styled from 'styled-components';
import { getFormatDate } from '../library/Librabry';
import { NoteContext } from '../components/NoteContext';
import AlertBox from './AlertBox';
import SearchBar from './SearchBar';

function InputNotes() {
	const noteFn = useContext(NoteContext);
	const [ date, setDate ] = useState([]);
	const [ text, setText ] = useState('');
	const [ open, setOpen ] = useState(false);

	const addNote = (action) => {
		//console.log('noteFn.note.text--->', noteFn.note.text === undefined, action);

		noteFn.setActiveFolder('');
		if (action === 'click' && noteFn.note.text) {
			//console.log('action---->', action, 'text:', text, 'save text:', noteFn.note.text);
			return;
		}

		//temp while id is generated by the db
		console.log('newnote:-------->>>>>>>>', noteFn.currentId, noteFn.note.folder ? noteFn.note.folder : noteFn.currentFolder );
		const newNote = {
			id: noteFn.currentId,
			text: text,
			date: new Date().toString(),
			folder: noteFn.note.folder ? noteFn.note.folder : noteFn.currentFolder 
		};
		noteFn.setNote(newNote);
		noteFn.setActiveClass('active');
		noteFn.notesDispatch({ type: 'ADD_NOTE', payload: newNote });
	};

	const checkIfNoteEntered = () => {
		//console.log('-------->', 'text:', text, '----->', noteFn.note);
		let text1 = text ? text.split('\n').join('') : '';
		let text2 = Object.keys(noteFn.note).length > 0 ? noteFn.note.text.split('\n').join('') : '';
		if (text1 !== text2 && text1.length > 0) {
			setOpen(true);
		} else if (noteFn.note.text === '' || noteFn.note.text === undefined) {
			noteFn.deleteNote();
		}
	};

	const checkKeyPressed = (e) => {
		console.log(e.key);
		if (e.key === 'Enter') {
			console.log('save data enter key was pressed');
			addNote('change');
		}
	};

	const handleCancel = () => {
		console.log('handleCancel');
		setOpen(false);
		noteFn.textRef.current.focus();
	};

	const handleConfirm = () => {
		console.log('handleConfirm', noteFn.note);
		setText(noteFn.note.text);
		setOpen(false);
	};

	useEffect(
		() => {
			//console.log('use effect input note', noteFn.note, text || noteFn.note.text);
			const d = noteFn.note.date ? noteFn.note.date : new Date().toString();
			setDate([ getFormatDate(d), d ]);
			//console.log('TEXT', text, '<----->', noteFn.note.text);
			setText(noteFn.note.text || '');
		},
		[ noteFn.note, noteFn.search]
	);

	return (
		<MyNotes>
			<AlertBox
				classType={`alert-box ${open ? '' : 'hide-box'}`}
				title={`Unsaved changes found!`}
				subtitle={'Click "Cancel" and save the last changes by pressing "Enter".'}
				cancelTxt={'Cancel'}
				deleteTxt={'Continue'}
				handleCancel={handleCancel}
				handleConfirm={handleConfirm}
				icon={'./alert.png'}
			/>
			<SearchBar />
			<div className="current-date">{date[0]}</div>
			<textarea
				ref={noteFn.textRef}
				className="myInputDiv"
				name="textarea"
				value={text || noteFn.note.text || ''}
				onChange={(e) => setText(e.target.value)}
				onClick={() => addNote('click')}
				onBlur={checkIfNoteEntered}
				onKeyDown={checkKeyPressed}
			/>
		</MyNotes>
	);
}

export default InputNotes;

const MyNotes = styled.div`
	background: #f9faf8;
	height: 100vh;
	.current-date {
		text-align: center;
		background: #fafbf9;
		font-size: 0.7em;
		color: #00000075;
		margin-top: 2px;
	}
	.myInputDiv {
		width: 100%;
		height: 100%;
		box-sizing: border-box;
		border: #fafbf9;
		background: #fafbf9;
		padding: 4px 20px;
		font-size: 0.7em;
	}
	textarea:focus,
	input:focus {
		outline: none;
	}
`;
